server:
  port: 8000
spring:
  application:
    name: smart-notification

  datasource:
    url: jdbc:postgresql://10.103.15.83:5432/smart_notification
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

liquibase:
  change-log: classpath:db/changelog/master.yaml
  enabled: true
  default-schema: public